[metadata]
name = pyrentri
version = 0.1.0
description = Simple API Wrapper for RENTRI (Registro Elettronico Nazionale per la Tracciabilità dei Rifiuti)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/progressify/pyrentri
license = MIT
author = Progressify
author_email = antonio@progressify.dev
keywords = rentri, api, sdk
classifiers =
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.7
[options]
zip_safe = False
python_requires = >= 3.7
test_suite = tests
packages =
    pyrentri
install_requires =
    configparser
    requests
    cryptography
    PyJWT
[bdist_wheel]
universal=0
